plugins {
    id 'org.springframework.boot'
    id 'io.spring.dependency-management'
    id 'java'
}

dependencies {
    // Web
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-security'

    // Persistence
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    // implementation 'org.springframework.boot:spring-boot-flyway'
    // implementation 'org.flywaydb:flyway-core'
    // implementation 'org.flywaydb:flyway-database-postgresql'
    // runtimeOnly 'org.postgresql:postgresql'

    // Axon
    //implementation "org.axonframework:axon:5.1.1"

    // Cache
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'

    // Messaging
    implementation 'org.springframework.kafka:spring-kafka'

    // API Documentation
    // implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.9'

    // Resilience
    // implementation 'io.github.resilience4j:resilience4j-spring-boot3:2.3.0'

    // Testing
    // testImplementation 'org.springframework.boot:spring-boot-starter-test'
    // testImplementation 'org.springframework.kafka:spring-kafka-test'
    testImplementation 'com.tngtech.archunit:archunit-junit5:1.4.1'
    testImplementation 'org.testcontainers:junit-jupiter'
    // testImplementation 'org.testcontainers:postgresql'
    // testImplementation 'org.testcontainers:kafka'
    // testImplementation 'com.redis:testcontainers-redis:2.2.4'
}

dependencyManagement {
    imports {
        mavenBom "org.testcontainers:testcontainers-bom:1.20.6"
    }
}
