spring:
  cloud:
    function:
      definition: reservationCreatedConsumer
    stream:
      default-binder: kafka
      bindings:
        reservationCreatedConsumer-in-0:
          destination: parking-facilities.reservation.created.v1
          group: prs-ms-ecommerce
          content-type: application/json
      kafka:
        binder:
          brokers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
        bindings:
          reservationCreatedConsumer-in-0:
            consumer:
              autoCommitOffset: true
