spring:
  config:
    import: configserver:${CLOUD_CONFIG_SERVER_URI:http://localhost:8888}
  cloud:
    config:
      name: prs-ms-pricing-config,actuator-config,jpa-config,redis-config,spring-doc-config,resource-server-config
