axon:
  axonserver:
    enabled: false

  serializer:
    general: jackson
    events: jackson
    messages: jackson

  kafka:
    bootstrap-servers: ${spring.cloud.stream.kafka.binder.brokers:localhost:9092}
    client-id: ${spring.application.name}
    default-topic: domain-events
    publisher:
      confirmation-mode: transactional
    producer:
      transaction-id-prefix: ${spring.application.name}-axon-
      # los eventos se mandan a Kafka de forma síncrona, esperando la confirmación de que han sido recibidos
      event-processor-mode: tracking
      properties:
        acks: all
        enable.idempotence: true
    # consumer:
    #   group-id: ${spring.application.name}
    #   # los eventos de Kafka se leen en background y Axon guarda el progreso en token_entry
    #   event-processor-mode: tracking
    #   properties:
    #     auto.offset.reset: earliest
