security:
  cors:
    allowed-origins:
      - http://localhost:3000
      - http://localhost:3001
    allowedOriginPatterns:
      - http://localhost:*
    allowed-methods:
      - GET
      - POST
      - PUT
      - PATCH
      - DELETE
      - OPTIONS
    allowed-headers:
      - Authorization
      - Content-Type
      - X-Requested-With
    exposed-headers:
      - Location
    allow-credentials: true
    max-age: 3600
