server:
  port: 8081

spring:
  application:
    name: prs-ms-parking-facilities
  config:
    import:
      - classpath:application-axon.yml

  datasource:
    url: jdbc:postgresql://localhost:5432/facilities_db
    username: ${DB_USERNAME:parking}
    password: ${DB_PASSWORD:parking}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: false
    hibernate:
      #ddl-auto: none
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        #default_schema: facilities
        format_sql: true
        highlight_sql: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      username: default
      password: ${REDIS_PASSWORD:redis_pass}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      properties:
        enable:
          idempotence: true
#    consumer:
#      group-id: catalog-service
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

catalog:
  search:
    max-page-size: 100
    default-limit: 20
    low-availability-threshold: 5
  cache:
    facility-ttl-seconds: 300
  reservation:
    hold-minutes: 5
    slot-size-minutes: 30
    short-duration-threshold-hours: 12
