spring:
  config:
    import: configserver:${CLOUD_CONFIG_SERVER_URI:http://localhost:8888}
  cloud:
    config:
      name: prs-ms-parking-facilities-config,actuator-config,redis-config,axon-config,spring-doc-config,resource-server-config